import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { cn } from "@/lib/utils";
import React from "react";
import { Toaster } from "sonner";
import Header from "@/components/header";
import Footer from "@/components/footer";

const cabinetGroteskFont = localFont({
  variable: "--cabinet-grotesk-font",
  display: "swap",
  src: [
    {
      path: "../fonts/CabinetGrotesk-Variable.ttf",
      weight: "variable",
    },
  ],
});

const satoshiFont = localFont({
  variable: "--satoshi-font",
  display: "swap",
  src: [
    {
      path: "../fonts/Satoshi-Variable.ttf",
      weight: "variable",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn(cabinetGroteskFont.className, satoshiFont.className)}>
        <div className="relative">
          <Header />
          {children}
          <Footer />
          <Toaster className="font-satoshi" />
        </div>
      </body>
    </html>
  );
}
